[build]
  command = "pnpm run build:netlify"
  # Only build on main branch to avoid unnecessary builds on feature branches
#  ignore = "test \"$BRANCH\" != \"main\""
  functions = "dist/netlify/functions"
  publish = "dist/client"

[dev]
  command = "pnpm run dev"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
