import type { ProviderConfigSchema } from '../types';

export const anthropicProviderSchema: ProviderConfigSchema = {
  type: 'llm',
  providerType: 'anthropic',
  displayName: 'Anthropic',
  description: 'Connect to Anthropic Claude models for advanced reasoning and analysis',
  icon: '🧠',
  color: '#D97757',
  defaultConfig: {
    model: 'claude-3-5-sonnet-20241022',
    maxTokens: 4096,
    temperature: 1.0,
  },
  fields: [
    {
      name: 'apiKey',
      label: 'API Key',
      type: 'password',
      required: true,
      description: 'Your Anthropic API key from console.anthropic.com',
      placeholder: 'sk-ant-...',
      group: 'Authentication',
    },
    {
      name: 'model',
      label: 'Model',
      type: 'model-autocomplete',
      required: true,
      description: 'Select or enter the Claude model to use. Models are automatically fetched from your API.',
      placeholder: 'claude-3-5-sonnet-20241022, claude-3-opus-20240229...',
      defaultValue: 'claude-3-5-sonnet-20241022',
      group: 'Model Configuration',
      componentProps: {
        providerType: 'anthropic',
      },
    },
    {
      name: 'maxTokens',
      label: 'Max Tokens',
      type: 'number',
      required: true,
      description: 'Maximum number of tokens to generate in the response',
      placeholder: '4096',
      defaultValue: 4096,
      validation: { min: 1, max: 8192 },
      group: 'Model Configuration',
    },
    {
      name: 'temperature',
      label: 'Temperature',
      type: 'number',
      required: false,
      description: 'Controls randomness (0 = deterministic, 1 = creative)',
      placeholder: '1.0',
      defaultValue: 1.0,
      validation: { min: 0, max: 1 },
      group: 'Model Configuration',
    },
    {
      name: 'topP',
      label: 'Top P',
      type: 'number',
      required: false,
      description: 'Controls diversity via nucleus sampling (0-1)',
      placeholder: '1',
      defaultValue: 1,
      validation: { min: 0, max: 1 },
      group: 'Model Configuration',
    },
    {
      name: 'topK',
      label: 'Top K',
      type: 'number',
      required: false,
      description: 'Only sample from the top K options for each subsequent token',
      placeholder: '5',
      validation: { min: 0 },
      group: 'Model Configuration',
    },
  ],
};
