import type { ProviderConfigSchema } from '../types';

const LETTA_CLOUD_URL = 'https://api.letta.com/v1';
const LETTA_LOCAL_URL = 'http://localhost:8283';

export const lettaProviderSchema: ProviderConfigSchema = {
    type: 'llm',
    providerType: 'letta',
    displayName: 'Letta',
    description: 'Connect your bot to a Letta agent — a stateful LLM with configurable conversation sessions.',
    icon: '🧠',
    color: '#9B59B6',
    defaultConfig: {
        deployment: 'local',
        apiUrl: LETTA_LOCAL_URL,
    },
    fields: [
        {
            name: 'deployment',
            label: 'Deployment',
            type: 'select',
            required: true,
            description: 'Choose where your Letta server is running',
            group: 'Connection',
            defaultValue: 'local',
            options: [
                { value: 'local', label: '🏠 Self-Hosted', description: 'Local Letta container (docker compose up -d letta)' },
                { value: 'cloud', label: '☁️ Letta Cloud', description: 'Hosted at api.letta.com — sign up at app.letta.com' },
            ],
            linkedDefaults: {
                targetField: 'apiUrl',
                values: { local: LETTA_LOCAL_URL, cloud: LETTA_CLOUD_URL },
            },
        },
        {
            name: 'apiUrl',
            label: 'API URL',
            type: 'url',
            required: true,
            description: 'Your Letta API base URL',
            placeholder: LETTA_LOCAL_URL,
            group: 'Connection',
        },
        {
            name: 'apiKey',
            label: 'API Key / Server Password',
            type: 'password',
            required: true,
            description: 'Letta Cloud API key (sk-let-...) or self-hosted server password (LETTA_SERVER_PASSWORD)',
            placeholder: 'sk-let-... or your server password',
            group: 'Authentication',
        },
        {
            name: 'agentId',
            label: 'Agent ID',
            type: 'text',
            required: true,
            description: 'The ID of your Letta agent',
            placeholder: 'agent-...',
            group: 'Agent',
            helperAction: {
                type: 'fetch',
                label: '🔍 Lookup Agent',
                description: 'Fetch the first available agent from your Letta account',
                endpoint: '/api/letta/agents',
                method: 'GET',
                targetField: 'agentId',
                valuePath: 'id',
            },
        },
        {
            name: 'sessionMode',
            label: 'Session Mode',
            type: 'select',
            required: false,
            description: 'How conversation history is scoped. Per-channel and per-user create separate Letta conversations automatically.',
            group: 'Session',
            defaultValue: 'default',
            options: [
                { value: 'default', label: 'Default', description: 'All messages share the agent default conversation' },
                { value: 'per-channel', label: 'Per Channel', description: 'One conversation per channel — bots remember each channel separately' },
                { value: 'per-user', label: 'Per User', description: 'One conversation per user — ideal for DMs or personal bots' },
                { value: 'fixed', label: 'Fixed', description: 'Use a specific named conversation ID for all messages' },
            ],
        },
        {
            name: 'conversationId',
            label: 'Conversation ID',
            type: 'text',
            required: false,
            description: 'Letta conversation ID to use when Session Mode is "Fixed"',
            placeholder: 'conv-...',
            group: 'Session',
            dependsOn: { field: 'sessionMode', value: 'fixed' },
        },
        {
            name: 'timeout',
            label: 'Request Timeout',
            type: 'number',
            required: false,
            description: 'Request timeout in milliseconds (default: 30000)',
            placeholder: '30000',
            group: 'Advanced',
        },
    ],
};
