import type { ProviderConfigSchema } from '../types';

export const lettaProviderSchema: ProviderConfigSchema = {
    type: 'llm',
    providerType: 'letta',
    displayName: 'Letta',
    description: 'Connect your bot to a Letta agent — a stateful LLM with configurable conversation sessions.',
    icon: '🧠',
    color: '#9B59B6',
    defaultConfig: {
        apiUrl: 'https://api.letta.com/v1',
    },
    fields: [
        {
            name: 'apiUrl',
            label: 'API URL',
            type: 'url',
            required: true,
            description: 'Your Letta API base URL (use https://api.letta.com/v1 for Letta Cloud)',
            placeholder: 'https://api.letta.com/v1',
            group: 'Connection',
        },
        {
            name: 'apiKey',
            label: 'API Key',
            type: 'password',
            required: true,
            description: 'Your Letta API key',
            placeholder: 'sk-let-...',
            group: 'Authentication',
        },
        {
            name: 'agentId',
            label: 'Agent ID',
            type: 'text',
            required: true,
            description: 'The ID of your Letta agent',
            placeholder: 'agent-...',
            group: 'Agent',
            helperAction: {
                type: 'fetch',
                label: '🔍 Lookup Agent',
                description: 'Fetch the first available agent from your Letta account',
                endpoint: '/api/letta/agents',
                method: 'GET',
                targetField: 'agentId',
                valuePath: 'id',
            },
        },
        {
            name: 'sessionMode',
            label: 'Session Mode',
            type: 'select',
            required: false,
            description: 'How conversation history is scoped. Per-channel and per-user create separate Letta conversations automatically.',
            group: 'Session',
            defaultValue: 'default',
            options: [
                { value: 'default', label: 'Default', description: 'All messages share the agent default conversation' },
                { value: 'per-channel', label: 'Per Channel', description: 'One conversation per channel — bots remember each channel separately' },
                { value: 'per-user', label: 'Per User', description: 'One conversation per user — ideal for DMs or personal bots' },
                { value: 'fixed', label: 'Fixed', description: 'Use a specific named conversation ID for all messages' },
            ],
        },
        {
            name: 'conversationId',
            label: 'Conversation ID',
            type: 'text',
            required: false,
            description: 'Letta conversation ID to use when Session Mode is "Fixed"',
            placeholder: 'conv-...',
            group: 'Session',
            dependsOn: { field: 'sessionMode', value: 'fixed' },
        },
        {
            name: 'timeout',
            label: 'Request Timeout',
            type: 'number',
            required: false,
            description: 'Request timeout in milliseconds (default: 30000)',
            placeholder: '30000',
            group: 'Advanced',
        },
    ],
};
