import type { ProviderConfigSchema } from '../types';

export const mem0ProviderSchema: ProviderConfigSchema = {
    type: 'memory',
    providerType: 'mem0',
    displayName: 'Mem0',
    description: 'Persistent memory for AI agents — automatically extracts and stores facts, preferences, and context.',
    icon: '🧩',
    color: '#2ECC71',
    defaultConfig: {
        llmProvider: 'openai',
        llmModel: 'gpt-4o-mini',
        embedderModel: 'text-embedding-3-small',
        vectorStoreProvider: 'memory',
    },
    fields: [
        {
            name: 'apiKey',
            label: 'OpenAI API Key',
            type: 'password',
            required: true,
            description: 'API key used for LLM fact extraction and embeddings',
            placeholder: 'sk-...',
            group: 'Authentication',
        },
        {
            name: 'llmProvider',
            label: 'LLM Provider',
            type: 'select',
            required: false,
            description: 'LLM used to extract facts from conversations',
            group: 'Model',
            defaultValue: 'openai',
            options: [
                { value: 'openai', label: 'OpenAI' },
                { value: 'anthropic', label: 'Anthropic' },
            ],
        },
        {
            name: 'llmModel',
            label: 'LLM Model',
            type: 'text',
            required: false,
            description: 'Model name for fact extraction',
            placeholder: 'gpt-4o-mini',
            group: 'Model',
        },
        {
            name: 'embedderModel',
            label: 'Embedder Model',
            type: 'text',
            required: false,
            description: 'Model used to generate memory embeddings',
            placeholder: 'text-embedding-3-small',
            group: 'Model',
        },
        {
            name: 'embedderBaseUrl',
            label: 'Embedder Base URL',
            type: 'url',
            required: false,
            description: 'Custom embedding endpoint (OpenAI-compatible, e.g., vLLM, Ollama, Voyage)',
            placeholder: 'http://localhost:8000/v1',
            group: 'Embeddings',
        },
        {
            name: 'embeddingProviderId',
            label: 'Embedding Provider ID',
            type: 'text',
            required: false,
            description: 'Reference to an LLM provider for embeddings (e.g., "openai", "letta")',
            placeholder: 'openai',
            group: 'Embeddings',
        },
        {
            name: 'llmProfileKey',
            label: 'LLM Profile Key',
            type: 'text',
            required: false,
            description: 'LLM profile key for embedding configuration',
            placeholder: 'default',
            group: 'Embeddings',
        },
        {
            name: 'vectorStoreProvider',
            label: 'Vector Store',
            type: 'select',
            required: false,
            description: 'Where to store memory vectors',
            group: 'Storage',
            defaultValue: 'memory',
            options: [
                { value: 'memory', label: 'In-Memory (ephemeral)' },
                { value: 'qdrant', label: 'Qdrant' },
                { value: 'pinecone', label: 'Pinecone' },
            ],
        },
        {
            name: 'userId',
            label: 'Default User ID',
            type: 'text',
            required: false,
            description: 'Default user scope for stored memories',
            placeholder: 'user-123',
            group: 'Scoping',
        },
        {
            name: 'agentId',
            label: 'Default Agent ID',
            type: 'text',
            required: false,
            description: 'Default agent scope for stored memories',
            placeholder: 'agent-abc',
            group: 'Scoping',
        },
        {
            name: 'historyDbPath',
            label: 'History DB Path',
            type: 'text',
            required: false,
            description: 'Path to SQLite file for memory change history (optional)',
            placeholder: './mem0-history.db',
            group: 'Advanced',
        },
    ],
};
