import type { ProviderConfigSchema } from '../types';

export const mem0ProviderSchema: ProviderConfigSchema = {
    type: 'memory',
    providerType: 'mem0',
    displayName: 'Mem0',
    description: 'Persistent memory for AI agents — automatically extracts and stores facts, preferences, and context.',
    icon: '🧩',
    color: '#2ECC71',
    defaultConfig: {
        baseUrl: 'https://api.mem0.ai/v1',
        timeoutMs: 30000,
        maxRetries: 3,
    },
    fields: [
        {
            name: 'apiKey',
            label: 'API Key',
            type: 'password',
            required: true,
            description: 'Mem0 API key (sent as Token auth header)',
            placeholder: 'm0-...',
            group: 'Authentication',
        },
        {
            name: 'baseUrl',
            label: 'Base URL',
            type: 'url',
            required: false,
            description: 'Mem0 API base URL (default: https://api.mem0.ai/v1)',
            placeholder: 'https://api.mem0.ai/v1',
            defaultValue: 'https://api.mem0.ai/v1',
            group: 'Connection',
        },
        {
            name: 'orgId',
            label: 'Organization ID',
            type: 'text',
            required: false,
            description: 'Optional organization ID sent as X-Org-Id header',
            placeholder: 'org-...',
            group: 'Authentication',
        },
        {
            name: 'userId',
            label: 'Default User ID',
            type: 'text',
            required: false,
            description: 'Default user scope for stored memories',
            placeholder: 'user-123',
            group: 'Scoping',
        },
        {
            name: 'agentId',
            label: 'Default Agent ID',
            type: 'text',
            required: false,
            description: 'Default agent scope for stored memories',
            placeholder: 'agent-abc',
            group: 'Scoping',
        },
        {
            name: 'timeoutMs',
            label: 'Request Timeout (ms)',
            type: 'number',
            required: false,
            description: 'API request timeout in milliseconds (default: 30000)',
            placeholder: '30000',
            defaultValue: 30000,
            group: 'Advanced',
        },
        {
            name: 'maxRetries',
            label: 'Max Retries',
            type: 'number',
            required: false,
            description: 'Maximum retry attempts for failed requests (default: 3)',
            placeholder: '3',
            defaultValue: 3,
            group: 'Advanced',
        },
    ],
};
