import type { ProviderConfigSchema } from '../types';

export const mem0ProviderSchema: ProviderConfigSchema = {
    type: 'memory',
    providerType: 'mem0',
    displayName: 'Mem0',
    description: 'Persistent memory for AI agents — automatically extracts and stores facts, preferences, and context.',
    icon: '🧩',
    color: '#2ECC71',
    fields: [
        {
            name: 'apiKey',
            label: 'Mem0 API Key',
            type: 'password',
            required: true,
            description: 'Mem0 platform API key (from app.mem0.ai), sent as the Authorization token',
            placeholder: 'm0-...',
            group: 'Authentication',
        },
        {
            name: 'baseUrl',
            label: 'Base URL',
            type: 'url',
            required: false,
            description: 'Base URL of the Mem0 REST API (override for self-hosted instances)',
            placeholder: 'https://api.mem0.ai/v1',
            group: 'Connection',
        },
        {
            name: 'orgId',
            label: 'Organization ID',
            type: 'text',
            required: false,
            description: 'Optional organisation ID, sent as the X-Org-Id header on every request',
            placeholder: 'org-...',
            group: 'Connection',
        },
        {
            name: 'userId',
            label: 'Default User ID',
            type: 'text',
            required: false,
            description: 'Default user scope for stored memories',
            placeholder: 'user-123',
            group: 'Scoping',
        },
        {
            name: 'agentId',
            label: 'Default Agent ID',
            type: 'text',
            required: false,
            description: 'Default agent scope for stored memories',
            placeholder: 'agent-abc',
            group: 'Scoping',
        },
        {
            name: 'timeoutMs',
            label: 'Request Timeout (ms)',
            type: 'number',
            required: false,
            description: 'Per-request timeout in milliseconds before the call is aborted',
            defaultValue: 30000,
            group: 'Advanced',
        },
        {
            name: 'maxRetries',
            label: 'Max Retries',
            type: 'number',
            required: false,
            description: 'Maximum number of retries on 429 / 5xx responses',
            defaultValue: 3,
            group: 'Advanced',
        },
    ],
};
