import type { ProviderConfigSchema } from '../types';

export const mem4aiProviderSchema: ProviderConfigSchema = {
    type: 'memory',
    providerType: 'mem4ai',
    displayName: 'Mem4ai',
    description: 'LLM-friendly memory management with adaptive personalization and flexible metadata tagging.',
    icon: '🏷️',
    color: '#3498DB',
    defaultConfig: {
        limit: 10,
        adaptivePersonalization: true,
        timeout: 30000,
    },
    fields: [
        {
            name: 'apiUrl',
            label: 'API URL',
            type: 'url',
            required: true,
            description: 'Mem4ai API endpoint',
            placeholder: 'https://api.mem4ai.com/v1',
            group: 'Connection',
        },
        {
            name: 'apiKey',
            label: 'API Key',
            type: 'password',
            required: true,
            description: 'Mem4ai API key for authentication',
            placeholder: 'mem4ai-...',
            group: 'Authentication',
        },
        {
            name: 'organizationId',
            label: 'Organization ID',
            type: 'text',
            required: false,
            description: 'Optional organization ID sent as X-Organization-ID header',
            placeholder: 'org-...',
            group: 'Authentication',
        },
        {
            name: 'userId',
            label: 'Default User ID',
            type: 'text',
            required: false,
            description: 'Default user scope for memory operations',
            placeholder: 'user-123',
            group: 'Scoping',
        },
        {
            name: 'agentId',
            label: 'Default Agent ID',
            type: 'text',
            required: false,
            description: 'Default agent scope for memory operations',
            placeholder: 'agent-abc',
            group: 'Scoping',
        },
        {
            name: 'embeddingProviderId',
            label: 'Embedding Provider ID',
            type: 'text',
            required: false,
            description: 'LLM profile key to use for embedding-driven memory operations',
            placeholder: 'openai-profile',
            group: 'Advanced',
        },
        {
            name: 'limit',
            label: 'Default Result Limit',
            type: 'number',
            required: false,
            description: 'Maximum memories returned per query (default: 10)',
            placeholder: '10',
            group: 'Advanced',
        },
        {
            name: 'timeout',
            label: 'Request Timeout (ms)',
            type: 'number',
            required: false,
            description: 'API request timeout in milliseconds (default: 30000)',
            placeholder: '30000',
            group: 'Advanced',
        },
    ],
};
