import { ProviderSchema } from '../types';

export const memvaultProviderSchema: ProviderSchema = {
    id: 'memvault',
    name: 'MemVault',
    description: 'RAG memory via PostgreSQL + pgvector with hybrid vector/recency scoring.',
    icon: '🗄️',
    color: '#3B82F6',
    defaultConfig: {
        host: 'localhost',
        port: 5432,
        vectorDimension: 1536,
        vectorWeight: 0.8,
        recencyWeight: 0.2,
    },
    fields: [
        {
            name: 'host',
            label: 'PostgreSQL Host',
            type: 'text',
            required: true,
            description: 'PostgreSQL server hostname',
            placeholder: 'localhost',
            group: 'Connection',
        },
        {
            name: 'port',
            label: 'Port',
            type: 'number',
            required: false,
            description: 'PostgreSQL server port',
            placeholder: '5432',
            group: 'Connection',
        },
        {
            name: 'database',
            label: 'Database',
            type: 'text',
            required: true,
            description: 'PostgreSQL database name',
            placeholder: 'memvault',
            group: 'Connection',
        },
        {
            name: 'user',
            label: 'Username',
            type: 'text',
            required: true,
            description: 'PostgreSQL username',
            placeholder: 'postgres',
            group: 'Connection',
        },
        {
            name: 'password',
            label: 'Password',
            type: 'password',
            required: true,
            description: 'PostgreSQL password',
            placeholder: '••••••••',
            group: 'Connection',
            sensitive: true,
        },
        {
            name: 'vectorDimension',
            label: 'Vector Dimension',
            type: 'number',
            required: false,
            description: 'Embedding vector dimension (e.g., 1536 for OpenAI text-embedding-3-small)',
            placeholder: '1536',
            group: 'Scoring',
        },
        {
            name: 'vectorWeight',
            label: 'Vector Weight',
            type: 'number',
            required: false,
            description: 'Weight for vector similarity score (default: 0.8)',
            placeholder: '0.8',
            group: 'Scoring',
        },
        {
            name: 'recencyWeight',
            label: 'Recency Weight',
            type: 'number',
            required: false,
            description: 'Weight for recency decay score (default: 0.2)',
            placeholder: '0.2',
            group: 'Scoring',
        },
        {
            name: 'embeddingEndpoint',
            label: 'Embedding Endpoint',
            type: 'url',
            required: false,
            description: 'Custom embedding API endpoint (optional, uses LLM profile if not set)',
            placeholder: 'https://api.openai.com/v1',
            group: 'Embeddings',
        },
        {
            name: 'embeddingApiKey',
            label: 'Embedding API Key',
            type: 'password',
            required: false,
            description: 'API key for embedding endpoint (optional)',
            placeholder: 'sk-...',
            group: 'Embeddings',
            sensitive: true,
        },
        {
            name: 'embeddingModel',
            label: 'Embedding Model',
            type: 'text',
            required: false,
            description: 'Embedding model name (e.g., text-embedding-3-small)',
            placeholder: 'text-embedding-3-small',
            group: 'Embeddings',
        },
        {
            name: 'llmProfileKey',
            label: 'LLM Profile Key',
            type: 'text',
            required: false,
            description: 'Reference to an LLM profile for embeddings (optional)',
            placeholder: 'default',
            group: 'Embeddings',
        },
    ],
};
