apiVersion: apps/v1
kind: Deployment
metadata:
  name: hivemind
  labels:
    app: hivemind
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hivemind
  template:
    metadata:
      labels:
        app: hivemind
    spec:
      containers:
      - name: hivemind
        image: hivemind:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        envFrom:
        - secretRef:
            name: hivemind-secrets
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: hivemind-service
spec:
  selector:
    app: hivemind
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer