export const ERROR_CODES = {
  ENOENT: 'ENOENT',
  NOT_FOUND: 'not found',
} as const;

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
} as const;

export const HEALTH_THRESHOLDS = {
  HIGH_FAILURE_COUNT: 3,
  RECENT_ERRORS_WARNING: 10,
  VALIDATION_ERRORS_WARNING: 3,
  ERROR_RATE_DEGRADED: 5,
  ERROR_RATE_WARNING: 1,
  RECENT_ERRORS_DEGRADED: 5,
  DOMINANT_ERROR_PERCENTAGE: 50,
} as const;
