export const RESPONSE_PROFILE_OVERRIDE_KEYS = [
  'MESSAGE_DELAY_MULTIPLIER',
  'MESSAGE_MIN_DELAY',
  'MESSAGE_MAX_DELAY',
  'MESSAGE_COMPOUNDING_DELAY_BASE_MS',
  'MESSAGE_COMPOUNDING_DELAY_MAX_MS',
  'MESSAGE_READING_DELAY_BASE_MS',
  'MESSAGE_READING_DELAY_PER_CHAR_MS',
  'MESSAGE_READING_DELAY_MIN_MS',
  'MESSAGE_READING_DELAY_MAX_MS',
  'MESSAGE_RATE_LIMIT_PER_CHANNEL',
  'MESSAGE_ONLY_WHEN_SPOKEN_TO',
  'MESSAGE_ONLY_WHEN_SPOKEN_TO_GRACE_WINDOW_MS',
  'MESSAGE_UNSOLICITED_BASE_CHANCE',
  'MESSAGE_UNSOLICITED_ADDRESSED',
  'MESSAGE_UNSOLICITED_UNADDRESSED',
  'MESSAGE_UNSOLICITED_SILENCE_PARTICIPANT_WINDOW_MS',
  'MESSAGE_SHORT_LENGTH_PENALTY',
  'MESSAGE_BOT_RESPONSE_MODIFIER',
  'MESSAGE_OTHERS_TYPING_WINDOW_MS',
  'MESSAGE_OTHERS_TYPING_MAX_WAIT_MS',
] as const;

export type ResponseProfileOverrideKey = typeof RESPONSE_PROFILE_OVERRIDE_KEYS[number];

export const RESPONSE_PROFILE_KEY_TYPES: Record<ResponseProfileOverrideKey, 'number' | 'boolean'> = {
  MESSAGE_DELAY_MULTIPLIER: 'number',
  MESSAGE_MIN_DELAY: 'number',
  MESSAGE_MAX_DELAY: 'number',
  MESSAGE_COMPOUNDING_DELAY_BASE_MS: 'number',
  MESSAGE_COMPOUNDING_DELAY_MAX_MS: 'number',
  MESSAGE_READING_DELAY_BASE_MS: 'number',
  MESSAGE_READING_DELAY_PER_CHAR_MS: 'number',
  MESSAGE_READING_DELAY_MIN_MS: 'number',
  MESSAGE_READING_DELAY_MAX_MS: 'number',
  MESSAGE_RATE_LIMIT_PER_CHANNEL: 'number',
  MESSAGE_ONLY_WHEN_SPOKEN_TO: 'boolean',
  MESSAGE_ONLY_WHEN_SPOKEN_TO_GRACE_WINDOW_MS: 'number',
  MESSAGE_UNSOLICITED_BASE_CHANCE: 'number',
  MESSAGE_UNSOLICITED_ADDRESSED: 'boolean',
  MESSAGE_UNSOLICITED_UNADDRESSED: 'boolean',
  MESSAGE_UNSOLICITED_SILENCE_PARTICIPANT_WINDOW_MS: 'number',
  MESSAGE_SHORT_LENGTH_PENALTY: 'number',
  MESSAGE_BOT_RESPONSE_MODIFIER: 'number',
  MESSAGE_OTHERS_TYPING_WINDOW_MS: 'number',
  MESSAGE_OTHERS_TYPING_MAX_WAIT_MS: 'number',
};

export const isResponseProfileOverrideKey = (key: string): key is ResponseProfileOverrideKey =>
  (RESPONSE_PROFILE_OVERRIDE_KEYS as readonly string[]).includes(key);
