export default {
  DISCORD_BOT_TOKEN: process.env.DISCORD_BOT_TOKEN || '',
  DISCORD_CLIENT_ID: process.env.DISCORD_CLIENT_ID || '',
  DISCORD_GUILD_ID: process.env.DISCORD_GUILD_ID || '',
  DISCORD_AUDIO_FILE_PATH: process.env.DISCORD_AUDIO_FILE_PATH || '',
  DISCORD_WELCOME_MESSAGE: process.env.DISCORD_WELCOME_MESSAGE || '',
  DISCORD_MESSAGE_HISTORY_LIMIT: process.env.DISCORD_MESSAGE_HISTORY_LIMIT ? parseInt(process.env.DISCORD_MESSAGE_HISTORY_LIMIT) : 10
};
