import fs from 'fs';
import path from 'path';

/**
 * Parses all convict configuration files in `src/config/` and extracts
 * environment variables, their documentation strings, and defaults.
 *
 * Returns an array of config objects.
 */
export function extractEnvVarsFromConfig(): Array<{
  name: string;
  doc: string;
  defaultVal: string | boolean | number | null;
  file: string;
}> {
  const configDir = path.join(process.cwd(), 'src', 'config');
  const files = fs.readdirSync(configDir).filter(f => f.endsWith('.ts'));

  const results: Array<{
    name: string;
    doc: string;
    defaultVal: string | boolean | number | null;
    file: string;
  }> = [];

  for (const file of files) {
    const content = fs.readFileSync(path.join(configDir, file), 'utf8');
    const lines = content.split('\n');

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      const envMatch = line.match(/env:\s*['"]([^'"]+)['"]/);

      if (envMatch && envMatch[1]) {
        const envName = envMatch[1];

        // Skip dynamically templated bot properties
        if (envName.startsWith('BOTS_') && envName.includes('{name}')) continue;

        let doc = '';
        let defaultVal: string | boolean | number | null = null;

        // Search surrounding lines for doc and default
        // We look UPwards for doc:
        for (let j = Math.max(0, i - 15); j <= i + 5; j++) {
          const docMatch = lines[j].match(/doc:\s*['"]([^'"]+)['"]/);
          if (docMatch && docMatch[1]) {
            doc = docMatch[1];
            break;
          }
        }

        // We look UPwards for default:
        for (let j = Math.max(0, i - 15); j <= i + 5; j++) {
          const defaultMatch = lines[j].match(/default:\s*(['"]?[^,'"\s]+['"]?)/);
          if (defaultMatch && defaultMatch[1]) {
            let parsed = defaultMatch[1].replace(/['"]/g, '');
            if (parsed === 'true') defaultVal = true;
            else if (parsed === 'false') defaultVal = false;
            else if (parsed === 'null') defaultVal = null;
            else if (!isNaN(Number(parsed))) defaultVal = Number(parsed);
            else defaultVal = parsed;
            break;
          }
        }

        results.push({
          name: envName,
          doc: doc || 'No description provided.',
          defaultVal,
          file,
        });
      }
    }
  }

  // Deduplicate by name
  const seen = new Set<string>();
  const uniqueResults = [];
  for (const result of results) {
    if (!seen.has(result.name)) {
      seen.add(result.name);
      uniqueResults.push(result);
    }
  }

  // Sort alphabetically
  return uniqueResults.sort((a, b) => a.name.localeCompare(b.name));
}

export function generateMarkdownDocumentation(): string {
  const vars = extractEnvVarsFromConfig();

  let markdown = `# Environment Variable Reference\n\n`;
  markdown += `This document is auto-generated by \`scripts/generate-env-docs.ts\` and checked in CI.\n`;
  markdown += `It provides a comprehensive list of all environment variables supported by the system based on the application's config schemas.\n\n`;

  // Group by file
  const grouped = vars.reduce((acc, curr) => {
    if (!acc[curr.file]) acc[curr.file] = [];
    acc[curr.file].push(curr);
    return acc;
  }, {} as Record<string, Array<{ name: string; doc: string; defaultVal: string | boolean | number | null; file: string; }>>);

  for (const [file, fileVars] of Object.entries(grouped).sort()) {
    markdown += `## ${file.replace('.ts', '')} Configuration\n\n`;
    markdown += `| Variable | Default | Description |\n`;
    markdown += `| :--- | :--- | :--- |\n`;

    for (const v of fileVars) {
      const defDisplay = v.defaultVal === null ? '`null`' : (typeof v.defaultVal === 'string' && v.defaultVal.trim() === '' ? '*(empty)*' : `\`${v.defaultVal}\``);
      markdown += `| \`${v.name}\` | ${defDisplay} | ${v.doc} |\n`;
    }
    markdown += `\n`;
  }

  return markdown;
}

if (require.main === module) {
  const docsPath = path.join(process.cwd(), 'docs', 'ENVIRONMENT_VARIABLES.md');
  const markdown = generateMarkdownDocumentation();
  fs.writeFileSync(docsPath, markdown, 'utf8');
  console.log(`Successfully generated environment variable documentation at ${docsPath}`);
}
